# Generated by Django 5.2.6 on 2025-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidop', models.CharField(max_length=45)),
                ('apellidom', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45)),
                ('contrasenia', models.TextField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
