# Generated by Django 5.2.6 on 2025-11-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(max_length=300, upload_to='productos_img/'),
        ),
    ]
